<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_transfer_request_tests.TestTransferRequestTest-20250423161649" tests="7" file="test_transfer_request_tests.py" time="0.117" timestamp="2025-04-23T16:16:49" failures="5" errors="0" skipped="0">
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_duplicated_transfer_test" time="0.003" timestamp="2025-04-23T16:16:49"/>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_transfer_yesterday_test" time="0.002" timestamp="2025-04-23T16:16:49"/>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_parametrized_cases_tests [TC1VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'80aa1316175acf4400a458ff09c17959' != 'c3bf5dc526788307d43527a2ef0c9b16'
- 80aa1316175acf4400a458ff09c17959
+ c3bf5dc526788307d43527a2ef0c9b16
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 539, in subTest
    yield
  File "/Users/aryanverma/Desktop/code/G89.2025.T18.GE3/src/unittest/python/test_transfer_request_tests.py", line 69, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 1251, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: '80aa1316175acf4400a458ff09c17959' != 'c3bf5dc526788307d43527a2ef0c9b16'
- 80aa1316175acf4400a458ff09c17959
+ c3bf5dc526788307d43527a2ef0c9b16

]]></failure>
	</testcase>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_parametrized_cases_tests [TC2VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'3950c494d708b425f95625acd38f16b9' != '2eaefb2ffedfdb4d6b94d51d00073118'
- 3950c494d708b425f95625acd38f16b9
+ 2eaefb2ffedfdb4d6b94d51d00073118
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 539, in subTest
    yield
  File "/Users/aryanverma/Desktop/code/G89.2025.T18.GE3/src/unittest/python/test_transfer_request_tests.py", line 69, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 1251, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: '3950c494d708b425f95625acd38f16b9' != '2eaefb2ffedfdb4d6b94d51d00073118'
- 3950c494d708b425f95625acd38f16b9
+ 2eaefb2ffedfdb4d6b94d51d00073118

]]></failure>
	</testcase>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_parametrized_cases_tests [TC3VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'822d570c3eb974b92004122711a05468' != '414b0952091f50db994f4eec3b2f803c'
- 822d570c3eb974b92004122711a05468
+ 414b0952091f50db994f4eec3b2f803c
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 539, in subTest
    yield
  File "/Users/aryanverma/Desktop/code/G89.2025.T18.GE3/src/unittest/python/test_transfer_request_tests.py", line 69, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 1251, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: '822d570c3eb974b92004122711a05468' != '414b0952091f50db994f4eec3b2f803c'
- 822d570c3eb974b92004122711a05468
+ 414b0952091f50db994f4eec3b2f803c

]]></failure>
	</testcase>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_parametrized_cases_tests [TC4VALID]" time="0.107" timestamp="2025-04-23T16:16:49">
		<failure type="AssertionError" message="'07bfd8df611c4fa73cde0b3e6cda1e18' != 'e810b089c7ab57e775551aa122d1914f'
- 07bfd8df611c4fa73cde0b3e6cda1e18
+ e810b089c7ab57e775551aa122d1914f
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 539, in subTest
    yield
  File "/Users/aryanverma/Desktop/code/G89.2025.T18.GE3/src/unittest/python/test_transfer_request_tests.py", line 69, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 1251, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: '07bfd8df611c4fa73cde0b3e6cda1e18' != 'e810b089c7ab57e775551aa122d1914f'
- 07bfd8df611c4fa73cde0b3e6cda1e18
+ e810b089c7ab57e775551aa122d1914f

]]></failure>
	</testcase>
	<testcase classname="test_transfer_request_tests.TestTransferRequestTest" name="test_transfer_for_today" time="0.004" timestamp="2025-04-23T16:16:49">
		<failure type="AssertionError" message="'c5477f9dcde7275021eab0bd58bb8175' != 'f8da119c45b3b6a483d810b7002a25e5'
- c5477f9dcde7275021eab0bd58bb8175
+ f8da119c45b3b6a483d810b7002a25e5
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/freezegun/api.py", line 885, in wrapper
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Users/aryanverma/Desktop/code/G89.2025.T18.GE3/src/unittest/python/test_transfer_request_tests.py", line 174, in test_transfer_for_today
    self.assertEqual("c5477f9dcde7275021eab0bd58bb8175",res)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 1251, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 'c5477f9dcde7275021eab0bd58bb8175' != 'f8da119c45b3b6a483d810b7002a25e5'
- c5477f9dcde7275021eab0bd58bb8175
+ f8da119c45b3b6a483d810b7002a25e5

]]></failure>
	</testcase>
</testsuite>
